export const images = {
  authAppleLogo: require("../../assets/icons/auth/apple-logo-50.png"),
  authFacebookLogo: require("../../assets/icons/auth/facebook-50.png"),
  authGoogleLogo: require("../../assets/icons/auth/google-logo-50.png"),
  authMailIcon: require("../../assets/icons/auth/mail-50.png"),
  authUsernameIcon: require("../../assets/icons/auth/username-48.png"),
  authPasswordIcon: require("../../assets/icons/auth/password-50.png"),
  onboardingWelcomeWomen: require("../../assets/images/onboarding/welcome-women.png"),
  onboardingFloatingMascot: require("../../assets/mascot/mascot-floating.png"),
  onboardingProfileWelcomeMascot: require("../../assets/mascot/mascot-welcome.png"),
  weraLogoWithName: require("../../assets/logos/wera-logo-with-name.png"),
  onboardingWelcomeMen: require("../../assets/images/onboarding/welcome-men.png"),
  onboardingPhotoGuideModel: require("../../assets/images/onboarding/photo-guide/01-model.png"),
  onboardingModelCreationTopWear: require("../../assets/images/onboarding/model-creation/model-creation-top-wear.png"),
  onboardingModelCreationBottomWear: require("../../assets/images/onboarding/model-creation/model-creation-bottom-wear.png"),
  onboardingModelCreationShoes: require("../../assets/images/onboarding/model-creation/model-creation-shoes.png"),
  weraModelFeminineBuildSlim: require("../../assets/wera-model/body/feminine/wera_woman_build_slim.png"),
  weraModelFeminineBuildLean: require("../../assets/wera-model/body/feminine/wera_woman_build_lean.png"),
  weraModelFeminineBuildAverage: require("../../assets/wera-model/body/feminine/wera_woman_build_average.png"),
  weraModelFeminineBuildAthletic: require("../../assets/wera-model/body/feminine/wera_woman_build_athletic.png"),
  weraModelFeminineBuildFull: require("../../assets/wera-model/body/feminine/wera_woman_build_full.png"),
  weraModelMasculineBuildSlim: require("../../assets/wera-model/body/masculine/wera_man_build_slim.png"),
  weraModelMasculineBuildLean: require("../../assets/wera-model/body/masculine/wera_man_build_lean.png"),
  weraModelMasculineBuildAverage: require("../../assets/wera-model/body/masculine/wera_man_build_average.png"),
  weraModelMasculineBuildAthletic: require("../../assets/wera-model/body/masculine/wera_man_build_athletic.png"),
  weraModelMasculineBuildFull: require("../../assets/wera-model/body/masculine/wera_man_build_full.png"),
} as const;
